name: Validate domains.yaml

on: [push, pull_request]

jobs:
  test:
    name: Test domains.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install poetry
        run: pip install poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Check formatting
        run: black --check .

      - name: Check mypy
        run: mypy .

      - name: Test with pytest
        run: pytest
